// auth.js
export const FETCH_ROLES = 'FETCH_ROLES'
export const FETCH_ROLES_SUCCESS = 'FETCH_ROLES_SUCCESS'
export const FETCH_ROLES_FAILURE = 'FETCH_ROLES_FAILURE'
export const UPDATE_ROLES = 'UPDATE_ROLES'

export const GET_ROLES_IMPORT = 'GET_ROLES_IMPORT'


// auth.js
export const FETCH_PERMISSIONS = 'FETCH_PERMISSIONS'
export const FETCH_PERMISSIONS_SUCCESS = 'FETCH_PERMISSIONS_SUCCESS'
export const FETCH_PERMISSIONS_FAILURE = 'FETCH_PERMISSIONS_FAILURE'
export const UPDATE_PERMISSIONS = 'UPDATE_PERMISSIONS'

export const GET_PERMISSIONS_IMPORT = 'GET_PERMISSIONS_IMPORT'


export const CLEAR_ALL = 'CLEAR_ALL'
