// auth.js
export const FETCH_CUSTOMER = 'FETCH_CUSTOMER'
export const FETCH_CUSTOMER_SUCCESS = 'FETCH_CUSTOMER_SUCCESS'
export const FETCH_CUSTOMER_FAILURE = 'FETCH_CUSTOMER_FAILURE'
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER' 

export const CLEAR_ALL = 'CLEAR_ALL'