// auth.js
export const FETCH_USERS = 'FETCH_USERS'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'
export const UPDATE_USERS = 'UPDATE_USERS'

export const CLEAR_ALL = 'CLEAR_ALL'
