export const FETCH_SHIPPING_LIST = 'FETCH_SHIPPING_LIST'
export const FETCH_SHIPPING_LIST_SUCCESS = 'FETCH_SHIPPING_LIST_SUCCESS'
export const FETCH_SHIPPING_LIST_FAILURE = 'FETCH_SHIPPING_LIST_FAILURE'
export const UPDATE_SHIPPING_LIST = 'UPDATE_SHIPPING_LIST'

export const FETCH_PACKING_LIST = 'FETCH_PACKING_LIST'
export const FETCH_PACKING_LIST_SUCCESS = 'FETCH_PACKING_LIST_SUCCESS'
export const FETCH_PACKING_LIST_FAILURE = 'FETCH_PACKING_LIST_FAILURE'
export const UPDATE_PACKING_LIST = 'UPDATE_PACKING_LIST'


export const CLEAR_ALL = 'CLEAR_ALL'
