// auth.js
export const FETCH_BRANCH = 'FETCH_BRANCH'
export const FETCH_BRANCH_SUCCESS = 'FETCH_BRANCH_SUCCESS'
export const FETCH_BRANCH_FAILURE = 'FETCH_BRANCH_FAILURE'
export const UPDATE_BRANCH = 'UPDATE_BRANCH'

export const GET_BRANCH_IMPORT = 'GET_BRANCH_IMPORT'

export const CLEAR_ALL = 'CLEAR_ALL'

export const FETCH_ALL_BRANCH = 'FETCH_ALL_BRANCH'
export const FETCH_ALL_BRANCH_SUCCESS = 'FETCH_ALL_BRANCH_SUCCESS'
export const FETCH_ALL_BRANCH_FAILURE = 'FETCH_ALL_BRANCH_FAILURE'
export const UPDATE_ALL_BRANCH = 'UPDATE_ALL_BRANCH' 

export const FETCH_PRICE_CATEGORY = 'FETCH_PRICE_CATEGORY'
export const FETCH_PRICE_CATEGORY_SUCCESS = 'FETCH_PRICE_CATEGORY_SUCCESS'
export const FETCH_PRICE_CATEGORY_FAILURE = 'FETCH_PRICE_CATEGORY_FAILURE'
export const UPDATE_PRICE_CATEGORY = 'UPDATE_PRICE_CATEGORY'



export const FETCH_LOOKUP = 'FETCH_LOOKUP'
export const FETCH_LOOKUP_SUCCESS = 'FETCH_LOOKUP_SUCCESS'
export const FETCH_LOOKUP_FAILURE = 'FETCH_LOOKUP_FAILURE'
export const UPDATE_LOOKUP = 'UPDATE_LOOKUP'