// auth.js
export const FETCH_BOOKING = 'FETCH_BOOKING'
export const FETCH_BOOKING_SUCCESS = 'FETCH_BOOKING_SUCCESS'
export const FETCH_BOOKING_FAILURE = 'FETCH_BOOKING_FAILURE'
export const UPDATE_BOOKING = 'UPDATE_BOOKING'

export const CLEAR_ALL = 'CLEAR_ALL'