// auth.js
export const FETCH_CUSTOMER_PRICE = 'FETCH_CUSTOMER_PRICE'
export const FETCH_CUSTOMER_PRICE_SUCCESS = 'FETCH_CUSTOMER_PRICE_SUCCESS'
export const FETCH_CUSTOMER_PRICE_FAILURE = 'FETCH_CUSTOMER_PRICE_FAILURE'
export const UPDATE_CUSTOMER_PRICE = 'UPDATE_CUSTOMER_PRICE' 

export const CLEAR_ALL = 'CLEAR_ALL'