// auth.js
export const FETCH_ITEMS = 'FETCH_ITEMS'
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS'
export const FETCH_ITEMS_FAILURE = 'FETCH_ITEMS_FAILURE'
export const UPDATE_ITEMS = 'UPDATE_ITEMS'

export const GET_ITEMS_IMPORT = 'GET_ITEMS_IMPORT'

export const CLEAR_ALL = 'CLEAR_ALL'

export const FETCH_ALL_ITEMS = 'FETCH_ALL_ITEMS'
export const FETCH_ALL_ITEMS_SUCCESS = 'FETCH_ALL_ITEMS_SUCCESS'
export const FETCH_ALL_ITEMS_FAILURE = 'FETCH_ALL_ITEMS_FAILURE'
export const UPDATE_ALL_ITEMS = 'UPDATE_ALL_ITEMS'